In [1]:
import numpy as np

In [8]:
def normalize(G):
    column_sums = G.sum(axis=0)

    n = G.shape[0]
    
    G_normalized = np.zeros_like(G, dtype=float)
    
    for i, sum_val in enumerate(column_sums):
        if sum_val == 0:
            G_normalized[:, i] = 1 / n
        else:
            G_normalized[:, i] = G[:, i] / sum_val
    
    return G_normalized 
        

Task5

In [35]:
G = np.array([[0,1,0,1]
             ,[1,0,1,0]
             ,[0,1,0,0]
             ,[0,0,1,0]])


print("G matrix",G)


G_hat = normalize(G)

print("G-hat matrix", G_hat)

A = 0.85 * G_hat + 0.15 * 1/G_hat.shape[0] * np.ones_like(G_hat)

print("A matrix", A)

eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvector = eigenvectors[:, np.isclose(eigenvalues, 1)]

res = np.real(eigenvector / eigenvector.sum())

# eigenvectors

# eigenvalues

res

G matrix [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 0]
 [0 0 1 0]]
G-hat matrix [[0.  0.5 0.  1. ]
 [1.  0.  0.5 0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.5 0. ]]
A matrix [[0.0375 0.4625 0.0375 0.8875]
 [0.8875 0.0375 0.4625 0.0375]
 [0.0375 0.4625 0.0375 0.0375]
 [0.0375 0.0375 0.4625 0.0375]]


array([[0.30174696],
       [0.37824246],
       [0.19825304],
       [0.12175754]])

So site 2 is the most important

Task 6

I expect site 4 to be the most important because all sites links to it, then site 3, then site 2 and 1.

In [37]:
G = np.array(
                 [[0,0,0,0]
                 ,[1,0,0,0]
                 ,[1,1,0,0]
                 ,[1,1,1,0]])


print("G matrix",G)


G_hat = normalize(G)

print("G-hat matrix", G_hat)

A = 0.85 * G_hat + 0.15 * 1/G_hat.shape[0] * np.ones_like(G_hat)

print("A matrix", A)

eigenvalues, eigenvectors = np.linalg.eig(A)

eigenvector = eigenvectors[:, np.isclose(eigenvalues, 1)]

res = np.real(eigenvector / eigenvector.sum())

# eigenvectors

# eigenvalues

res

G matrix [[0 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]]
G-hat matrix [[0.         0.         0.         0.25      ]
 [0.33333333 0.         0.         0.25      ]
 [0.33333333 0.5        0.         0.25      ]
 [0.33333333 0.5        1.         0.25      ]]
A matrix [[0.0375     0.0375     0.0375     0.25      ]
 [0.32083333 0.0375     0.0375     0.25      ]
 [0.32083333 0.4625     0.0375     0.25      ]
 [0.32083333 0.4625     0.8875     0.25      ]]


array([[0.13341746],
       [0.17121907],
       [0.24398718],
       [0.45137628]])

Task 7 (a)


In [41]:
G = np.array([[0,1,0,1]
                 ,[1,0,1,0]
                 ,[0,1,0,0]
                 ,[0,0,1,0]])


G_3 = G @ G @ G

print("G^3 matrix", G_3)

print("path from site 3 to 2 in 3 steps =", G_3[1,2])

G^3 matrix [[0 3 0 1]
 [2 0 3 0]
 [0 2 0 1]
 [1 0 1 0]]
path from site 3 to 2 in 3 steps = 3


Task 7 (b)

In [65]:
G = np.array(
    [[0,0,0,0]
        ,[1,0,0,0]
        ,[1,1,0,0]
        ,[1,1,1,0]])

res = 0

g = G.copy()

for i in range(3):
    res += G[3,0]
    print(f"G in power {i+1}",G)
    G = G @ g


print("path from site 1 to 4 in less then 3 steps =", res)

G in power 1 [[0 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]]
G in power 2 [[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [2 1 0 0]]
G in power 3 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]
path from site 1 to 4 in less then 3 steps = 4


Task 10 (b)

In [63]:
p = 0.55

q = 1-p

G = np.array(
     [[1,q,0,0,0]
     ,[0,0,q,0,0]
     ,[0,p,0,q,0]
     ,[0,0,p,0,0]
     ,[0,0,0,p,1]])


print("G matrix",G)


eigenvalues, eigenvectors = np.linalg.eig(G)

eigenvector = eigenvectors[:, np.isclose(eigenvalues, 1)]

res = np.real(eigenvector / eigenvector.sum())

# eigenvectors

# eigenvalues

eigenvector

# res

G matrix [[1.   0.45 0.   0.   0.  ]
 [0.   0.   0.45 0.   0.  ]
 [0.   0.55 0.   0.45 0.  ]
 [0.   0.   0.55 0.   0.  ]
 [0.   0.   0.   0.55 1.  ]]


array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

There are 2 eigenvectors with eigenvalue equal two one, which coresponds two equilibrium states. This means Perron–Frobenius theorem is not satisfied so we cnt use eigenvector approach to fing probability distribution.

In [70]:
p = 0.51

q = 1-p

initial_state = np.array([0,0,1,0,0])

G = np.array(
    [[1,q,0,0,0]
        ,[0,0,q,0,0]
        ,[0,p,0,q,0]
        ,[0,0,p,0,0]
        ,[0,0,0,p,1]])


g = G.copy()

print("G matrix",G)


for i in range(10):
    G = G @ g

print("G10 matrix",G)

res = G @ initial_state

res

G matrix [[1.   0.49 0.   0.   0.  ]
 [0.   0.   0.49 0.   0.  ]
 [0.   0.51 0.   0.49 0.  ]
 [0.   0.   0.51 0.   0.  ]
 [0.   0.   0.   0.51 1.  ]]
G10 matrix [[1.         0.72716924 0.46503772 0.22786848 0.        ]
 [0.         0.         0.0152819  0.         0.        ]
 [0.         0.01590565 0.         0.0152819  0.        ]
 [0.         0.         0.01590565 0.         0.        ]
 [0.         0.25692511 0.50377473 0.75684962 1.        ]]


array([0.46503772, 0.0152819 , 0.        , 0.01590565, 0.50377473])