In [2]:
import numpy as np
from sympy import *

# Define the matrix
A = np.array([[4,-3,1], [-1,0, 5], [-1,3,2]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Output the results
print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 3.  6. -3.]
Eigenvectors:
[[-0.81649658 -0.57735027 -0.40824829]
 [-0.40824829  0.57735027 -0.81649658]
 [-0.40824829  0.57735027  0.40824829]]


In [7]:
res = A @ eigenvectors[1]

res

array([-4.18154055, -3.67423461,  0.50730594])

In [25]:
vectors = eigenvectors.transpose()

vec = vectors[1]

np.array(vec) * -1

array([ 0.57735027, -0.57735027, -0.57735027])

In [26]:
res = A @ np.array(vec) * -1

res / 6

array([ 0.57735027, -0.57735027, -0.57735027])

In [1]:
import numpy as np

# Define the matrix
A = np.array([[2,1],[0,-3]])

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Output the results
print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 2. -3.]
Eigenvectors:
[[ 1.         -0.19611614]
 [ 0.          0.98058068]]


In [24]:
C_m = Matrix(np.array([[1,0,0],[0,1/2,0],[0,0,1/3]]))

C_m

Matrix([
[1.0,   0,                 0],
[  0, 0.5,                 0],
[  0,   0, 0.333333333333333]])

In [25]:
C_inv_m = C_m.inv()
C_inv_m

# print(A_inv_m.eigenvals())
# A_inv_m.eigenvects()

Matrix([
[1.0,   0,   0],
[  0, 2.0,   0],
[  0,   0, 3.0]])

In [26]:
A = Matrix(np.array([[-2,2,3],[2,-1,6],[3,6,1]]))

A

Matrix([
[-2,  2, 3],
[ 2, -1, 6],
[ 3,  6, 1]])

In [27]:
res = C_inv_m @ A @ C_m
# res = A @ C_inv_m
res

Matrix([
[-2.0,  1.0, 1.0],
[ 4.0, -1.0, 4.0],
[ 9.0,  9.0, 1.0]])

In [21]:
ans = C_m @ res

ans

Matrix([
[-2,  1, 1],
[ 4, -1, 4],
[ 9,  9, 1]])